//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.IFCDC.UI.AccionMejoraWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccionMejoraCollectionDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class AccionMejoraCollectionDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraDC[] LstAccionesMejoraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraDC[] LstAccionesMejora {
            get {
                return this.LstAccionesMejoraField;
            }
            set {
                if ((object.ReferenceEquals(this.LstAccionesMejoraField, value) != true)) {
                    this.LstAccionesMejoraField = value;
                    this.RaisePropertyChanged("LstAccionesMejora");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccionMejoraDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class AccionMejoraDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccionMejoraIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CicloEjecucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CicloEjecucionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoHallazgoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HallazgoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InformeFinCicloIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccionMejoraId {
            get {
                return this.AccionMejoraIdField;
            }
            set {
                if ((this.AccionMejoraIdField.Equals(value) != true)) {
                    this.AccionMejoraIdField = value;
                    this.RaisePropertyChanged("AccionMejoraId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CicloEjecucion {
            get {
                return this.CicloEjecucionField;
            }
            set {
                if ((object.ReferenceEquals(this.CicloEjecucionField, value) != true)) {
                    this.CicloEjecucionField = value;
                    this.RaisePropertyChanged("CicloEjecucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CicloEjecucionId {
            get {
                return this.CicloEjecucionIdField;
            }
            set {
                if ((this.CicloEjecucionIdField.Equals(value) != true)) {
                    this.CicloEjecucionIdField = value;
                    this.RaisePropertyChanged("CicloEjecucionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoHallazgo {
            get {
                return this.CodigoHallazgoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoHallazgoField, value) != true)) {
                    this.CodigoHallazgoField = value;
                    this.RaisePropertyChanged("CodigoHallazgo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HallazgoId {
            get {
                return this.HallazgoIdField;
            }
            set {
                if ((this.HallazgoIdField.Equals(value) != true)) {
                    this.HallazgoIdField = value;
                    this.RaisePropertyChanged("HallazgoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InformeFinCicloId {
            get {
                return this.InformeFinCicloIdField;
            }
            set {
                if ((this.InformeFinCicloIdField.Equals(value) != true)) {
                    this.InformeFinCicloIdField = value;
                    this.RaisePropertyChanged("InformeFinCicloId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccionMejoraReporteCollectionDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class AccionMejoraReporteCollectionDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraReporteDC[] LstAccionMejoraReporteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraReporteDC[] LstAccionMejoraReporte {
            get {
                return this.LstAccionMejoraReporteField;
            }
            set {
                if ((object.ReferenceEquals(this.LstAccionMejoraReporteField, value) != true)) {
                    this.LstAccionMejoraReporteField = value;
                    this.RaisePropertyChanged("LstAccionMejoraReporte");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccionMejoraReporteDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class AccionMejoraReporteDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccionMejoraIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoAccionMejoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoHallazgoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCursoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccionMejoraId {
            get {
                return this.AccionMejoraIdField;
            }
            set {
                if ((this.AccionMejoraIdField.Equals(value) != true)) {
                    this.AccionMejoraIdField = value;
                    this.RaisePropertyChanged("AccionMejoraId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAccionMejora {
            get {
                return this.CodigoAccionMejoraField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoAccionMejoraField, value) != true)) {
                    this.CodigoAccionMejoraField = value;
                    this.RaisePropertyChanged("CodigoAccionMejora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoHallazgo {
            get {
                return this.CodigoHallazgoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoHallazgoField, value) != true)) {
                    this.CodigoHallazgoField = value;
                    this.RaisePropertyChanged("CodigoHallazgo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCurso {
            get {
                return this.NombreCursoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCursoField, value) != true)) {
                    this.NombreCursoField = value;
                    this.RaisePropertyChanged("NombreCurso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccionMejoraWS.IAccionMejora")]
    public interface IAccionMejora {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccionMejora/WSRegistrarAccionMejora", ReplyAction="http://tempuri.org/IAccionMejora/WSRegistrarAccionMejoraResponse")]
        UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraCollectionDC WSRegistrarAccionMejora(int hallazgoId, int informeFinCicloId, int periodoEjecucionId, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccionMejora/WSListarAccionesMejoraxInformeFinCiclo", ReplyAction="http://tempuri.org/IAccionMejora/WSListarAccionesMejoraxInformeFinCicloResponse")]
        UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraCollectionDC WSListarAccionesMejoraxInformeFinCiclo(int informeFinCicloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccionMejora/WSListarAccionesMejoraPrevias", ReplyAction="http://tempuri.org/IAccionMejora/WSListarAccionesMejoraPreviasResponse")]
        UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraCollectionDC WSListarAccionesMejoraPrevias(int cursoId, int periodoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccionMejora/WSEditarAccionMejora", ReplyAction="http://tempuri.org/IAccionMejora/WSEditarAccionMejoraResponse")]
        UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraCollectionDC WSEditarAccionMejora(int accionMejoraId, int informeFinCicloId, int periodoEjecucionId, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccionMejora/WSEditarAccionMejoraPrevia", ReplyAction="http://tempuri.org/IAccionMejora/WSEditarAccionMejoraPreviaResponse")]
        UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraCollectionDC WSEditarAccionMejoraPrevia(int cursoId, int periodoId, int accionMejoraId, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccionMejora/WSEliminarAccionMejora", ReplyAction="http://tempuri.org/IAccionMejora/WSEliminarAccionMejoraResponse")]
        UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraCollectionDC WSEliminarAccionMejora(int accionMejoraId, int informeFinCicloId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccionMejora/WSListarAccionMejoraReporte", ReplyAction="http://tempuri.org/IAccionMejora/WSListarAccionMejoraReporteResponse")]
        UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraReporteCollectionDC WSListarAccionMejoraReporte(int cursoId, int periodoId, string estado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccionMejoraChannel : UPC.IFCDC.UI.AccionMejoraWS.IAccionMejora, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccionMejoraClient : System.ServiceModel.ClientBase<UPC.IFCDC.UI.AccionMejoraWS.IAccionMejora>, UPC.IFCDC.UI.AccionMejoraWS.IAccionMejora {
        
        public AccionMejoraClient() {
        }
        
        public AccionMejoraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccionMejoraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccionMejoraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccionMejoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraCollectionDC WSRegistrarAccionMejora(int hallazgoId, int informeFinCicloId, int periodoEjecucionId, string descripcion) {
            return base.Channel.WSRegistrarAccionMejora(hallazgoId, informeFinCicloId, periodoEjecucionId, descripcion);
        }
        
        public UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraCollectionDC WSListarAccionesMejoraxInformeFinCiclo(int informeFinCicloId) {
            return base.Channel.WSListarAccionesMejoraxInformeFinCiclo(informeFinCicloId);
        }
        
        public UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraCollectionDC WSListarAccionesMejoraPrevias(int cursoId, int periodoId) {
            return base.Channel.WSListarAccionesMejoraPrevias(cursoId, periodoId);
        }
        
        public UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraCollectionDC WSEditarAccionMejora(int accionMejoraId, int informeFinCicloId, int periodoEjecucionId, string descripcion) {
            return base.Channel.WSEditarAccionMejora(accionMejoraId, informeFinCicloId, periodoEjecucionId, descripcion);
        }
        
        public UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraCollectionDC WSEditarAccionMejoraPrevia(int cursoId, int periodoId, int accionMejoraId, string estado) {
            return base.Channel.WSEditarAccionMejoraPrevia(cursoId, periodoId, accionMejoraId, estado);
        }
        
        public UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraCollectionDC WSEliminarAccionMejora(int accionMejoraId, int informeFinCicloId) {
            return base.Channel.WSEliminarAccionMejora(accionMejoraId, informeFinCicloId);
        }
        
        public UPC.IFCDC.UI.AccionMejoraWS.AccionMejoraReporteCollectionDC WSListarAccionMejoraReporte(int cursoId, int periodoId, string estado) {
            return base.Channel.WSListarAccionMejoraReporte(cursoId, periodoId, estado);
        }
    }
}
