//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.IFCDC.UI.PeriodoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PeriodoCollectionDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract", ItemName="PeriodoDC")]
    [System.SerializableAttribute()]
    public class PeriodoCollectionDC : System.Collections.Generic.List<UPC.IFCDC.UI.PeriodoWS.PeriodoDC> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodoDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class PeriodoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EsActualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodoIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EsActual {
            get {
                return this.EsActualField;
            }
            set {
                if ((this.EsActualField.Equals(value) != true)) {
                    this.EsActualField = value;
                    this.RaisePropertyChanged("EsActual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFinField, value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaInicioField, value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodoId {
            get {
                return this.PeriodoIdField;
            }
            set {
                if ((this.PeriodoIdField.Equals(value) != true)) {
                    this.PeriodoIdField = value;
                    this.RaisePropertyChanged("PeriodoId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PeriodoWS.IPeriodo")]
    public interface IPeriodo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeriodo/ListarPeriodoPorCarreraId", ReplyAction="http://tempuri.org/IPeriodo/ListarPeriodoPorCarreraIdResponse")]
        UPC.IFCDC.UI.PeriodoWS.PeriodoCollectionDC ListarPeriodoPorCarreraId(int CarreraId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeriodo/ObtenerPeriodoActual", ReplyAction="http://tempuri.org/IPeriodo/ObtenerPeriodoActualResponse")]
        UPC.IFCDC.UI.PeriodoWS.PeriodoDC ObtenerPeriodoActual();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeriodo/WSListarPeriodos", ReplyAction="http://tempuri.org/IPeriodo/WSListarPeriodosResponse")]
        UPC.IFCDC.UI.PeriodoWS.PeriodoCollectionDC WSListarPeriodos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeriodo/WSObtenerPeriodoActual", ReplyAction="http://tempuri.org/IPeriodo/WSObtenerPeriodoActualResponse")]
        UPC.IFCDC.UI.PeriodoWS.PeriodoDC WSObtenerPeriodoActual();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeriodo/ListarPeriodoXEstadoXEsActual", ReplyAction="http://tempuri.org/IPeriodo/ListarPeriodoXEstadoXEsActualResponse")]
        UPC.IFCDC.UI.PeriodoWS.PeriodoCollectionDC ListarPeriodoXEstadoXEsActual(UPC.IFCDC.UI.PeriodoWS.PeriodoDC objDC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPeriodoChannel : UPC.IFCDC.UI.PeriodoWS.IPeriodo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeriodoClient : System.ServiceModel.ClientBase<UPC.IFCDC.UI.PeriodoWS.IPeriodo>, UPC.IFCDC.UI.PeriodoWS.IPeriodo {
        
        public PeriodoClient() {
        }
        
        public PeriodoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeriodoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeriodoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeriodoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UPC.IFCDC.UI.PeriodoWS.PeriodoCollectionDC ListarPeriodoPorCarreraId(int CarreraId) {
            return base.Channel.ListarPeriodoPorCarreraId(CarreraId);
        }
        
        public UPC.IFCDC.UI.PeriodoWS.PeriodoDC ObtenerPeriodoActual() {
            return base.Channel.ObtenerPeriodoActual();
        }
        
        public UPC.IFCDC.UI.PeriodoWS.PeriodoCollectionDC WSListarPeriodos() {
            return base.Channel.WSListarPeriodos();
        }
        
        public UPC.IFCDC.UI.PeriodoWS.PeriodoDC WSObtenerPeriodoActual() {
            return base.Channel.WSObtenerPeriodoActual();
        }
        
        public UPC.IFCDC.UI.PeriodoWS.PeriodoCollectionDC ListarPeriodoXEstadoXEsActual(UPC.IFCDC.UI.PeriodoWS.PeriodoDC objDC) {
            return base.Channel.ListarPeriodoXEstadoXEsActual(objDC);
        }
    }
}
