//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.CursoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CursoCollectionDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract", ItemName="CursoDC")]
    [System.SerializableAttribute()]
    public class CursoCollectionDC : System.Collections.Generic.List<ConsoleApplication1.CursoWS.CursoDC> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CursoDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class CursoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CursoControlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CursoCreditosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CursoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CursoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CursoVerificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CursoControl {
            get {
                return this.CursoControlField;
            }
            set {
                if ((this.CursoControlField.Equals(value) != true)) {
                    this.CursoControlField = value;
                    this.RaisePropertyChanged("CursoControl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CursoCreditos {
            get {
                return this.CursoCreditosField;
            }
            set {
                if ((this.CursoCreditosField.Equals(value) != true)) {
                    this.CursoCreditosField = value;
                    this.RaisePropertyChanged("CursoCreditos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CursoId {
            get {
                return this.CursoIdField;
            }
            set {
                if ((this.CursoIdField.Equals(value) != true)) {
                    this.CursoIdField = value;
                    this.RaisePropertyChanged("CursoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CursoNombre {
            get {
                return this.CursoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.CursoNombreField, value) != true)) {
                    this.CursoNombreField = value;
                    this.RaisePropertyChanged("CursoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CursoVerificacion {
            get {
                return this.CursoVerificacionField;
            }
            set {
                if ((this.CursoVerificacionField.Equals(value) != true)) {
                    this.CursoVerificacionField = value;
                    this.RaisePropertyChanged("CursoVerificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CursoWS.ICurso")]
    public interface ICurso {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurso/ListarCursosPorTipoCursoCarreraId", ReplyAction="http://tempuri.org/ICurso/ListarCursosPorTipoCursoCarreraIdResponse")]
        ConsoleApplication1.CursoWS.CursoCollectionDC ListarCursosPorTipoCursoCarreraId(int CarreraId, int TipoCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurso/ListarCursosPorCarreraPorNivelPorPeriodoActual", ReplyAction="http://tempuri.org/ICurso/ListarCursosPorCarreraPorNivelPorPeriodoActualResponse")]
        ConsoleApplication1.CursoWS.CursoCollectionDC ListarCursosPorCarreraPorNivelPorPeriodoActual(int CarreraId, int nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurso/ActualizarCursosPorCarreraPorNivelPorPeriodoActual", ReplyAction="http://tempuri.org/ICurso/ActualizarCursosPorCarreraPorNivelPorPeriodoActualRespo" +
            "nse")]
        void ActualizarCursosPorCarreraPorNivelPorPeriodoActual(int cursoId, bool esControl, bool esVerificacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICursoChannel : ConsoleApplication1.CursoWS.ICurso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CursoClient : System.ServiceModel.ClientBase<ConsoleApplication1.CursoWS.ICurso>, ConsoleApplication1.CursoWS.ICurso {
        
        public CursoClient() {
        }
        
        public CursoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CursoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication1.CursoWS.CursoCollectionDC ListarCursosPorTipoCursoCarreraId(int CarreraId, int TipoCurso) {
            return base.Channel.ListarCursosPorTipoCursoCarreraId(CarreraId, TipoCurso);
        }
        
        public ConsoleApplication1.CursoWS.CursoCollectionDC ListarCursosPorCarreraPorNivelPorPeriodoActual(int CarreraId, int nivel) {
            return base.Channel.ListarCursosPorCarreraPorNivelPorPeriodoActual(CarreraId, nivel);
        }
        
        public void ActualizarCursosPorCarreraPorNivelPorPeriodoActual(int cursoId, bool esControl, bool esVerificacion) {
            base.Channel.ActualizarCursosPorCarreraPorNivelPorPeriodoActual(cursoId, esControl, esVerificacion);
        }
    }
}
