#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.SSIA2013.DL.DataModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SSIA2012-1")]
	public partial class SSIA2013DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SSIA2013DataContext() : 
				base(global::UPC.SSIA2013.DL.DataModel.Properties.Settings.Default.SSIA2012_1ConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public SSIA2013DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SSIA2013DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SSIA2013DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SSIA2013DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Editar_AccionMejora")]
		public ISingleResult<up_Editar_AccionMejoraResult> up_Editar_AccionMejora([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccionMejoraId", DbType="Int")] System.Nullable<int> accionMejoraId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InformeFinCicloId", DbType="Int")] System.Nullable<int> informeFinCicloId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CicloEjecucionId", DbType="Int")] System.Nullable<int> cicloEjecucionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(500)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accionMejoraId, informeFinCicloId, cicloEjecucionId, descripcion);
			return ((ISingleResult<up_Editar_AccionMejoraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Registrar_Hallazgo")]
		public ISingleResult<up_Registrar_HallazgoResult> up_Registrar_Hallazgo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InformeFinCicloId", DbType="Int")] System.Nullable<int> informeFinCicloId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(500)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PeriodoId", DbType="Int")] System.Nullable<int> periodoId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), informeFinCicloId, descripcion, periodoId);
			return ((ISingleResult<up_Registrar_HallazgoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Editar_AccionMejora_Previa")]
		public ISingleResult<up_Editar_AccionMejora_PreviaResult> up_Editar_AccionMejora_Previa([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CursoId", DbType="Int")] System.Nullable<int> cursoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PeriodoId", DbType="Int")] System.Nullable<int> periodoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccionMejoraId", DbType="Int")] System.Nullable<int> accionMejoraId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(20)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cursoId, periodoId, accionMejoraId, estado);
			return ((ISingleResult<up_Editar_AccionMejora_PreviaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Editar_Hallazgo")]
		public ISingleResult<up_Editar_HallazgoResult> up_Editar_Hallazgo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HallazgoId", DbType="Int")] System.Nullable<int> hallazgoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(500)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InformeFinCicloId", DbType="Int")] System.Nullable<int> informeFinCicloId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hallazgoId, descripcion, informeFinCicloId);
			return ((ISingleResult<up_Editar_HallazgoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Editar_InformeFinCiclo")]
		public ISingleResult<up_Editar_InformeFinCicloResult> up_Editar_InformeFinCiclo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InformeFinCicloId", DbType="Int")] System.Nullable<int> informeFinCicloId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(20)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DesarrolloUnidades", DbType="VarChar(500)")] string desarrolloUnidades, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Infraestructura", DbType="VarChar(500)")] string infraestructura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Alumnos", DbType="VarChar(500)")] string alumnos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Delegados", DbType="VarChar(500)")] string delegados, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Encuesta", DbType="VarChar(500)")] string encuesta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), informeFinCicloId, estado, desarrolloUnidades, infraestructura, alumnos, delegados, encuesta);
			return ((ISingleResult<up_Editar_InformeFinCicloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Eliminar_AccionMejora")]
		public ISingleResult<up_Eliminar_AccionMejoraResult> up_Eliminar_AccionMejora([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccionMejoraId", DbType="Int")] System.Nullable<int> accionMejoraId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InformeFinCicloId", DbType="Int")] System.Nullable<int> informeFinCicloId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accionMejoraId, informeFinCicloId);
			return ((ISingleResult<up_Eliminar_AccionMejoraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Eliminar_Hallazgo")]
		public ISingleResult<up_Eliminar_HallazgoResult> up_Eliminar_Hallazgo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HallazgoId", DbType="Int")] System.Nullable<int> hallazgoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InformeFinCicloId", DbType="Int")] System.Nullable<int> informeFinCicloId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hallazgoId, informeFinCicloId);
			return ((ISingleResult<up_Eliminar_HallazgoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Listar_AccionMejora_Previas")]
		public ISingleResult<up_Listar_AccionMejora_PreviasResult> up_Listar_AccionMejora_Previas([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CursoId", DbType="Int")] System.Nullable<int> cursoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PeriodoId", DbType="Int")] System.Nullable<int> periodoId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cursoId, periodoId);
			return ((ISingleResult<up_Listar_AccionMejora_PreviasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Listar_AccionMejora_x_InformeFinCiclo")]
		public ISingleResult<up_Listar_AccionMejora_x_InformeFinCicloResult> up_Listar_AccionMejora_x_InformeFinCiclo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InformeFinCicloId", DbType="Int")] System.Nullable<int> informeFinCicloId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), informeFinCicloId);
			return ((ISingleResult<up_Listar_AccionMejora_x_InformeFinCicloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Listar_Cursos")]
		public ISingleResult<up_Listar_CursosResult> up_Listar_Cursos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<up_Listar_CursosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Listar_Cursos_x_Profesor")]
		public ISingleResult<up_Listar_Cursos_x_ProfesorResult> up_Listar_Cursos_x_Profesor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProfesorId", DbType="VarChar(50)")] string profesorId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), profesorId);
			return ((ISingleResult<up_Listar_Cursos_x_ProfesorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Listar_Hallazgos_x_InformeFinCiclo")]
		public ISingleResult<up_Listar_Hallazgos_x_InformeFinCicloResult> up_Listar_Hallazgos_x_InformeFinCiclo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InformeFinCicloId", DbType="Int")] System.Nullable<int> informeFinCicloId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), informeFinCicloId);
			return ((ISingleResult<up_Listar_Hallazgos_x_InformeFinCicloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Listar_Periodos")]
		public ISingleResult<up_Listar_PeriodosResult> up_Listar_Periodos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<up_Listar_PeriodosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Listar_Reporte_AccionMejora")]
		public ISingleResult<up_Listar_Reporte_AccionMejoraResult> up_Listar_Reporte_AccionMejora([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CursoId", DbType="Int")] System.Nullable<int> cursoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PeriodoId", DbType="Int")] System.Nullable<int> periodoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(20)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cursoId, periodoId, estado);
			return ((ISingleResult<up_Listar_Reporte_AccionMejoraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Listar_Reporte_Hallazgo")]
		public ISingleResult<up_Listar_Reporte_HallazgoResult> up_Listar_Reporte_Hallazgo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CursoId", DbType="Int")] System.Nullable<int> cursoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PeriodoId", DbType="Int")] System.Nullable<int> periodoId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cursoId, periodoId);
			return ((ISingleResult<up_Listar_Reporte_HallazgoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Listar_Reporte_InformeFinCiclo")]
		public ISingleResult<up_Listar_Reporte_InformeFinCicloResult> up_Listar_Reporte_InformeFinCiclo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CursoId", DbType="Int")] System.Nullable<int> cursoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PeriodoId", DbType="Int")] System.Nullable<int> periodoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(20)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cursoId, periodoId, estado);
			return ((ISingleResult<up_Listar_Reporte_InformeFinCicloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Listar_ResultadoPrograma_x_Curso")]
		public ISingleResult<up_Listar_ResultadoPrograma_x_CursoResult> up_Listar_ResultadoPrograma_x_Curso([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CursoId", DbType="Int")] System.Nullable<int> cursoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PeriodoId", DbType="Int")] System.Nullable<int> periodoId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cursoId, periodoId);
			return ((ISingleResult<up_Listar_ResultadoPrograma_x_CursoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Obtener_InformeFinCiclo")]
		public ISingleResult<up_Obtener_InformeFinCicloResult> up_Obtener_InformeFinCiclo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CoordinadorId", DbType="VarChar(50)")] string coordinadorId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CursoId", DbType="Int")] System.Nullable<int> cursoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PeriodoId", DbType="Int")] System.Nullable<int> periodoId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), coordinadorId, cursoId, periodoId);
			return ((ISingleResult<up_Obtener_InformeFinCicloResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Obtener_InformeFinCiclo_x_Id")]
		public ISingleResult<up_Obtener_InformeFinCiclo_x_IdResult> up_Obtener_InformeFinCiclo_x_Id([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InformeFinCicloId", DbType="Int")] System.Nullable<int> informeFinCicloId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), informeFinCicloId);
			return ((ISingleResult<up_Obtener_InformeFinCiclo_x_IdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Obtener_Logro_x_Curso")]
		public ISingleResult<up_Obtener_Logro_x_CursoResult> up_Obtener_Logro_x_Curso([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CursoId", DbType="Int")] System.Nullable<int> cursoId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cursoId);
			return ((ISingleResult<up_Obtener_Logro_x_CursoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Obtener_PeriodoActual")]
		public ISingleResult<up_Obtener_PeriodoActualResult> up_Obtener_PeriodoActual()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<up_Obtener_PeriodoActualResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Obtener_Persona")]
		public ISingleResult<up_Obtener_PersonaResult> up_Obtener_Persona([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PersonaId", DbType="VarChar(50)")] string personaId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), personaId);
			return ((ISingleResult<up_Obtener_PersonaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="IFCDC.up_Registrar_AccionMejora")]
		public ISingleResult<up_Registrar_AccionMejoraResult> up_Registrar_AccionMejora([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HallazgoId", DbType="Int")] System.Nullable<int> hallazgoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InformeFinCicloId", DbType="Int")] System.Nullable<int> informeFinCicloId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CicloEjecucionId", DbType="Int")] System.Nullable<int> cicloEjecucionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(500)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hallazgoId, informeFinCicloId, cicloEjecucionId, descripcion);
			return ((ISingleResult<up_Registrar_AccionMejoraResult>)(result.ReturnValue));
		}
	}
	
	public partial class up_Editar_AccionMejoraResult
	{
		
		private int _AccionMejoraId;
		
		private int _HallazgoId;
		
		private int _InformeFinCicloId;
		
		private int _CicloEjecucionId;
		
		private string _Codigo;
		
		private string _Descripcion;
		
		private string _Estado;
		
		private bool _EstaActivo;
		
		private string _CodigoHallazgo;
		
		private string _CicloEjecucion;
		
		public up_Editar_AccionMejoraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccionMejoraId", DbType="Int NOT NULL")]
		public int AccionMejoraId
		{
			get
			{
				return this._AccionMejoraId;
			}
			set
			{
				if ((this._AccionMejoraId != value))
				{
					this._AccionMejoraId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HallazgoId", DbType="Int NOT NULL")]
		public int HallazgoId
		{
			get
			{
				return this._HallazgoId;
			}
			set
			{
				if ((this._HallazgoId != value))
				{
					this._HallazgoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CicloEjecucionId", DbType="Int NOT NULL")]
		public int CicloEjecucionId
		{
			get
			{
				return this._CicloEjecucionId;
			}
			set
			{
				if ((this._CicloEjecucionId != value))
				{
					this._CicloEjecucionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstaActivo", DbType="Bit NOT NULL")]
		public bool EstaActivo
		{
			get
			{
				return this._EstaActivo;
			}
			set
			{
				if ((this._EstaActivo != value))
				{
					this._EstaActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoHallazgo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoHallazgo
		{
			get
			{
				return this._CodigoHallazgo;
			}
			set
			{
				if ((this._CodigoHallazgo != value))
				{
					this._CodigoHallazgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CicloEjecucion", DbType="VarChar(50)")]
		public string CicloEjecucion
		{
			get
			{
				return this._CicloEjecucion;
			}
			set
			{
				if ((this._CicloEjecucion != value))
				{
					this._CicloEjecucion = value;
				}
			}
		}
	}
	
	public partial class up_Registrar_HallazgoResult
	{
		
		private int _HallazgoId;
		
		private string _Codigo;
		
		private string _Descripcion;
		
		private int _InformeFinCicloId;
		
		private bool _EstaActivo;
		
		private int _PeriodoId;
		
		public up_Registrar_HallazgoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HallazgoId", DbType="Int NOT NULL")]
		public int HallazgoId
		{
			get
			{
				return this._HallazgoId;
			}
			set
			{
				if ((this._HallazgoId != value))
				{
					this._HallazgoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstaActivo", DbType="Bit NOT NULL")]
		public bool EstaActivo
		{
			get
			{
				return this._EstaActivo;
			}
			set
			{
				if ((this._EstaActivo != value))
				{
					this._EstaActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodoId", DbType="Int NOT NULL")]
		public int PeriodoId
		{
			get
			{
				return this._PeriodoId;
			}
			set
			{
				if ((this._PeriodoId != value))
				{
					this._PeriodoId = value;
				}
			}
		}
	}
	
	public partial class up_Editar_AccionMejora_PreviaResult
	{
		
		private int _AccionMejoraId;
		
		private int _HallazgoId;
		
		private int _InformeFinCicloId;
		
		private int _CicloEjecucionId;
		
		private string _Codigo;
		
		private string _Descripcion;
		
		private string _Estado;
		
		private bool _EstaActivo;
		
		private string _CodigoHallazgo;
		
		private string _CicloEjecucion;
		
		public up_Editar_AccionMejora_PreviaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccionMejoraId", DbType="Int NOT NULL")]
		public int AccionMejoraId
		{
			get
			{
				return this._AccionMejoraId;
			}
			set
			{
				if ((this._AccionMejoraId != value))
				{
					this._AccionMejoraId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HallazgoId", DbType="Int NOT NULL")]
		public int HallazgoId
		{
			get
			{
				return this._HallazgoId;
			}
			set
			{
				if ((this._HallazgoId != value))
				{
					this._HallazgoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CicloEjecucionId", DbType="Int NOT NULL")]
		public int CicloEjecucionId
		{
			get
			{
				return this._CicloEjecucionId;
			}
			set
			{
				if ((this._CicloEjecucionId != value))
				{
					this._CicloEjecucionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstaActivo", DbType="Bit NOT NULL")]
		public bool EstaActivo
		{
			get
			{
				return this._EstaActivo;
			}
			set
			{
				if ((this._EstaActivo != value))
				{
					this._EstaActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoHallazgo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoHallazgo
		{
			get
			{
				return this._CodigoHallazgo;
			}
			set
			{
				if ((this._CodigoHallazgo != value))
				{
					this._CodigoHallazgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CicloEjecucion", DbType="VarChar(50)")]
		public string CicloEjecucion
		{
			get
			{
				return this._CicloEjecucion;
			}
			set
			{
				if ((this._CicloEjecucion != value))
				{
					this._CicloEjecucion = value;
				}
			}
		}
	}
	
	public partial class up_Editar_HallazgoResult
	{
		
		private int _HallazgoId;
		
		private string _Codigo;
		
		private string _Descripcion;
		
		private int _InformeFinCicloId;
		
		private bool _EstaActivo;
		
		private int _PeriodoId;
		
		public up_Editar_HallazgoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HallazgoId", DbType="Int NOT NULL")]
		public int HallazgoId
		{
			get
			{
				return this._HallazgoId;
			}
			set
			{
				if ((this._HallazgoId != value))
				{
					this._HallazgoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstaActivo", DbType="Bit NOT NULL")]
		public bool EstaActivo
		{
			get
			{
				return this._EstaActivo;
			}
			set
			{
				if ((this._EstaActivo != value))
				{
					this._EstaActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodoId", DbType="Int NOT NULL")]
		public int PeriodoId
		{
			get
			{
				return this._PeriodoId;
			}
			set
			{
				if ((this._PeriodoId != value))
				{
					this._PeriodoId = value;
				}
			}
		}
	}
	
	public partial class up_Editar_InformeFinCicloResult
	{
		
		private int _InformeFinCicloId;
		
		private string _CoordinadorId;
		
		private int _CursoId;
		
		private int _PeriodoId;
		
		private string _DesarrolloUnidades;
		
		private string _ComentarioAlumnos;
		
		private string _ComentarioInfraestructura;
		
		private string _ComentarioDelegados;
		
		private string _ComentarioEscuesta;
		
		private string _Estado;
		
		private string _UltimaActualizacion;
		
		public up_Editar_InformeFinCicloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoordinadorId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CoordinadorId
		{
			get
			{
				return this._CoordinadorId;
			}
			set
			{
				if ((this._CoordinadorId != value))
				{
					this._CoordinadorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CursoId", DbType="Int NOT NULL")]
		public int CursoId
		{
			get
			{
				return this._CursoId;
			}
			set
			{
				if ((this._CursoId != value))
				{
					this._CursoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodoId", DbType="Int NOT NULL")]
		public int PeriodoId
		{
			get
			{
				return this._PeriodoId;
			}
			set
			{
				if ((this._PeriodoId != value))
				{
					this._PeriodoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DesarrolloUnidades", DbType="VarChar(500)")]
		public string DesarrolloUnidades
		{
			get
			{
				return this._DesarrolloUnidades;
			}
			set
			{
				if ((this._DesarrolloUnidades != value))
				{
					this._DesarrolloUnidades = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioAlumnos", DbType="VarChar(500)")]
		public string ComentarioAlumnos
		{
			get
			{
				return this._ComentarioAlumnos;
			}
			set
			{
				if ((this._ComentarioAlumnos != value))
				{
					this._ComentarioAlumnos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioInfraestructura", DbType="VarChar(500)")]
		public string ComentarioInfraestructura
		{
			get
			{
				return this._ComentarioInfraestructura;
			}
			set
			{
				if ((this._ComentarioInfraestructura != value))
				{
					this._ComentarioInfraestructura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioDelegados", DbType="VarChar(500)")]
		public string ComentarioDelegados
		{
			get
			{
				return this._ComentarioDelegados;
			}
			set
			{
				if ((this._ComentarioDelegados != value))
				{
					this._ComentarioDelegados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioEscuesta", DbType="VarChar(500)")]
		public string ComentarioEscuesta
		{
			get
			{
				return this._ComentarioEscuesta;
			}
			set
			{
				if ((this._ComentarioEscuesta != value))
				{
					this._ComentarioEscuesta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimaActualizacion", DbType="VarChar(30)")]
		public string UltimaActualizacion
		{
			get
			{
				return this._UltimaActualizacion;
			}
			set
			{
				if ((this._UltimaActualizacion != value))
				{
					this._UltimaActualizacion = value;
				}
			}
		}
	}
	
	public partial class up_Eliminar_AccionMejoraResult
	{
		
		private int _AccionMejoraId;
		
		private int _HallazgoId;
		
		private int _InformeFinCicloId;
		
		private int _CicloEjecucionId;
		
		private string _Codigo;
		
		private string _Descripcion;
		
		private string _Estado;
		
		private bool _EstaActivo;
		
		private string _CodigoHallazgo;
		
		private string _CicloEjecucion;
		
		public up_Eliminar_AccionMejoraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccionMejoraId", DbType="Int NOT NULL")]
		public int AccionMejoraId
		{
			get
			{
				return this._AccionMejoraId;
			}
			set
			{
				if ((this._AccionMejoraId != value))
				{
					this._AccionMejoraId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HallazgoId", DbType="Int NOT NULL")]
		public int HallazgoId
		{
			get
			{
				return this._HallazgoId;
			}
			set
			{
				if ((this._HallazgoId != value))
				{
					this._HallazgoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CicloEjecucionId", DbType="Int NOT NULL")]
		public int CicloEjecucionId
		{
			get
			{
				return this._CicloEjecucionId;
			}
			set
			{
				if ((this._CicloEjecucionId != value))
				{
					this._CicloEjecucionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstaActivo", DbType="Bit NOT NULL")]
		public bool EstaActivo
		{
			get
			{
				return this._EstaActivo;
			}
			set
			{
				if ((this._EstaActivo != value))
				{
					this._EstaActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoHallazgo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoHallazgo
		{
			get
			{
				return this._CodigoHallazgo;
			}
			set
			{
				if ((this._CodigoHallazgo != value))
				{
					this._CodigoHallazgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CicloEjecucion", DbType="VarChar(50)")]
		public string CicloEjecucion
		{
			get
			{
				return this._CicloEjecucion;
			}
			set
			{
				if ((this._CicloEjecucion != value))
				{
					this._CicloEjecucion = value;
				}
			}
		}
	}
	
	public partial class up_Eliminar_HallazgoResult
	{
		
		private int _HallazgoId;
		
		private string _Codigo;
		
		private string _Descripcion;
		
		private int _InformeFinCicloId;
		
		private bool _EstaActivo;
		
		private int _PeriodoId;
		
		public up_Eliminar_HallazgoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HallazgoId", DbType="Int NOT NULL")]
		public int HallazgoId
		{
			get
			{
				return this._HallazgoId;
			}
			set
			{
				if ((this._HallazgoId != value))
				{
					this._HallazgoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstaActivo", DbType="Bit NOT NULL")]
		public bool EstaActivo
		{
			get
			{
				return this._EstaActivo;
			}
			set
			{
				if ((this._EstaActivo != value))
				{
					this._EstaActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodoId", DbType="Int NOT NULL")]
		public int PeriodoId
		{
			get
			{
				return this._PeriodoId;
			}
			set
			{
				if ((this._PeriodoId != value))
				{
					this._PeriodoId = value;
				}
			}
		}
	}
	
	public partial class up_Listar_AccionMejora_PreviasResult
	{
		
		private int _AccionMejoraId;
		
		private int _HallazgoId;
		
		private int _InformeFinCicloId;
		
		private int _CicloEjecucionId;
		
		private string _Codigo;
		
		private string _Descripcion;
		
		private string _Estado;
		
		private bool _EstaActivo;
		
		private string _CodigoHallazgo;
		
		private string _CicloEjecucion;
		
		public up_Listar_AccionMejora_PreviasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccionMejoraId", DbType="Int NOT NULL")]
		public int AccionMejoraId
		{
			get
			{
				return this._AccionMejoraId;
			}
			set
			{
				if ((this._AccionMejoraId != value))
				{
					this._AccionMejoraId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HallazgoId", DbType="Int NOT NULL")]
		public int HallazgoId
		{
			get
			{
				return this._HallazgoId;
			}
			set
			{
				if ((this._HallazgoId != value))
				{
					this._HallazgoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CicloEjecucionId", DbType="Int NOT NULL")]
		public int CicloEjecucionId
		{
			get
			{
				return this._CicloEjecucionId;
			}
			set
			{
				if ((this._CicloEjecucionId != value))
				{
					this._CicloEjecucionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstaActivo", DbType="Bit NOT NULL")]
		public bool EstaActivo
		{
			get
			{
				return this._EstaActivo;
			}
			set
			{
				if ((this._EstaActivo != value))
				{
					this._EstaActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoHallazgo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoHallazgo
		{
			get
			{
				return this._CodigoHallazgo;
			}
			set
			{
				if ((this._CodigoHallazgo != value))
				{
					this._CodigoHallazgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CicloEjecucion", DbType="VarChar(50)")]
		public string CicloEjecucion
		{
			get
			{
				return this._CicloEjecucion;
			}
			set
			{
				if ((this._CicloEjecucion != value))
				{
					this._CicloEjecucion = value;
				}
			}
		}
	}
	
	public partial class up_Listar_AccionMejora_x_InformeFinCicloResult
	{
		
		private int _AccionMejoraId;
		
		private int _HallazgoId;
		
		private int _InformeFinCicloId;
		
		private int _CicloEjecucionId;
		
		private string _Codigo;
		
		private string _Descripcion;
		
		private string _Estado;
		
		private bool _EstaActivo;
		
		private string _CodigoHallazgo;
		
		private string _CicloEjecucion;
		
		public up_Listar_AccionMejora_x_InformeFinCicloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccionMejoraId", DbType="Int NOT NULL")]
		public int AccionMejoraId
		{
			get
			{
				return this._AccionMejoraId;
			}
			set
			{
				if ((this._AccionMejoraId != value))
				{
					this._AccionMejoraId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HallazgoId", DbType="Int NOT NULL")]
		public int HallazgoId
		{
			get
			{
				return this._HallazgoId;
			}
			set
			{
				if ((this._HallazgoId != value))
				{
					this._HallazgoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CicloEjecucionId", DbType="Int NOT NULL")]
		public int CicloEjecucionId
		{
			get
			{
				return this._CicloEjecucionId;
			}
			set
			{
				if ((this._CicloEjecucionId != value))
				{
					this._CicloEjecucionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstaActivo", DbType="Bit NOT NULL")]
		public bool EstaActivo
		{
			get
			{
				return this._EstaActivo;
			}
			set
			{
				if ((this._EstaActivo != value))
				{
					this._EstaActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoHallazgo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoHallazgo
		{
			get
			{
				return this._CodigoHallazgo;
			}
			set
			{
				if ((this._CodigoHallazgo != value))
				{
					this._CodigoHallazgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CicloEjecucion", DbType="VarChar(50)")]
		public string CicloEjecucion
		{
			get
			{
				return this._CicloEjecucion;
			}
			set
			{
				if ((this._CicloEjecucion != value))
				{
					this._CicloEjecucion = value;
				}
			}
		}
	}
	
	public partial class up_Listar_CursosResult
	{
		
		private int _CursoId;
		
		private string _Codigo;
		
		private string _Nombre;
		
		public up_Listar_CursosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CursoId", DbType="Int NOT NULL")]
		public int CursoId
		{
			get
			{
				return this._CursoId;
			}
			set
			{
				if ((this._CursoId != value))
				{
					this._CursoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(50)")]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(150)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class up_Listar_Cursos_x_ProfesorResult
	{
		
		private int _CursoId;
		
		private string _Codigo;
		
		private string _Nombre;
		
		private string _ProfesorId;
		
		public up_Listar_Cursos_x_ProfesorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CursoId", DbType="Int NOT NULL")]
		public int CursoId
		{
			get
			{
				return this._CursoId;
			}
			set
			{
				if ((this._CursoId != value))
				{
					this._CursoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(50)")]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(150)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfesorId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ProfesorId
		{
			get
			{
				return this._ProfesorId;
			}
			set
			{
				if ((this._ProfesorId != value))
				{
					this._ProfesorId = value;
				}
			}
		}
	}
	
	public partial class up_Listar_Hallazgos_x_InformeFinCicloResult
	{
		
		private int _HallazgoId;
		
		private string _Codigo;
		
		private string _Descripcion;
		
		private int _InformeFinCicloId;
		
		private bool _EstaActivo;
		
		private int _PeriodoId;
		
		public up_Listar_Hallazgos_x_InformeFinCicloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HallazgoId", DbType="Int NOT NULL")]
		public int HallazgoId
		{
			get
			{
				return this._HallazgoId;
			}
			set
			{
				if ((this._HallazgoId != value))
				{
					this._HallazgoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstaActivo", DbType="Bit NOT NULL")]
		public bool EstaActivo
		{
			get
			{
				return this._EstaActivo;
			}
			set
			{
				if ((this._EstaActivo != value))
				{
					this._EstaActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodoId", DbType="Int NOT NULL")]
		public int PeriodoId
		{
			get
			{
				return this._PeriodoId;
			}
			set
			{
				if ((this._PeriodoId != value))
				{
					this._PeriodoId = value;
				}
			}
		}
	}
	
	public partial class up_Listar_PeriodosResult
	{
		
		private int _PeriodoId;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estado;
		
		private System.Nullable<bool> _EsActual;
		
		private System.Nullable<System.DateTime> _FechaInicio;
		
		private System.Nullable<System.DateTime> _FechaFin;
		
		public up_Listar_PeriodosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodoId", DbType="Int NOT NULL")]
		public int PeriodoId
		{
			get
			{
				return this._PeriodoId;
			}
			set
			{
				if ((this._PeriodoId != value))
				{
					this._PeriodoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit")]
		public System.Nullable<bool> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsActual", DbType="Bit")]
		public System.Nullable<bool> EsActual
		{
			get
			{
				return this._EsActual;
			}
			set
			{
				if ((this._EsActual != value))
				{
					this._EsActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="Date")]
		public System.Nullable<System.DateTime> FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this._FechaInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFin", DbType="Date")]
		public System.Nullable<System.DateTime> FechaFin
		{
			get
			{
				return this._FechaFin;
			}
			set
			{
				if ((this._FechaFin != value))
				{
					this._FechaFin = value;
				}
			}
		}
	}
	
	public partial class up_Listar_Reporte_AccionMejoraResult
	{
		
		private int _AccionMejoraId;
		
		private string _CodigoAccionMejora;
		
		private string _Descripcion;
		
		private string _Estado;
		
		private string _CodigoHallazgo;
		
		private string _NombreCurso;
		
		public up_Listar_Reporte_AccionMejoraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccionMejoraId", DbType="Int NOT NULL")]
		public int AccionMejoraId
		{
			get
			{
				return this._AccionMejoraId;
			}
			set
			{
				if ((this._AccionMejoraId != value))
				{
					this._AccionMejoraId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoAccionMejora", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoAccionMejora
		{
			get
			{
				return this._CodigoAccionMejora;
			}
			set
			{
				if ((this._CodigoAccionMejora != value))
				{
					this._CodigoAccionMejora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoHallazgo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoHallazgo
		{
			get
			{
				return this._CodigoHallazgo;
			}
			set
			{
				if ((this._CodigoHallazgo != value))
				{
					this._CodigoHallazgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCurso", DbType="VarChar(150)")]
		public string NombreCurso
		{
			get
			{
				return this._NombreCurso;
			}
			set
			{
				if ((this._NombreCurso != value))
				{
					this._NombreCurso = value;
				}
			}
		}
	}
	
	public partial class up_Listar_Reporte_HallazgoResult
	{
		
		private int _HallazgoId;
		
		private string _CodigoHallazgo;
		
		private string _Descripcion;
		
		private string _NombreCurso;
		
		public up_Listar_Reporte_HallazgoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HallazgoId", DbType="Int NOT NULL")]
		public int HallazgoId
		{
			get
			{
				return this._HallazgoId;
			}
			set
			{
				if ((this._HallazgoId != value))
				{
					this._HallazgoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoHallazgo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoHallazgo
		{
			get
			{
				return this._CodigoHallazgo;
			}
			set
			{
				if ((this._CodigoHallazgo != value))
				{
					this._CodigoHallazgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCurso", DbType="VarChar(150)")]
		public string NombreCurso
		{
			get
			{
				return this._NombreCurso;
			}
			set
			{
				if ((this._NombreCurso != value))
				{
					this._NombreCurso = value;
				}
			}
		}
	}
	
	public partial class up_Listar_Reporte_InformeFinCicloResult
	{
		
		private int _InformeFinCicloId;
		
		private string _CodigoCurso;
		
		private string _NombreCurso;
		
		private string _NombreProfesor;
		
		private string _FechaActualizacion;
		
		private string _Estado;
		
		private string _Periodo;
		
		public up_Listar_Reporte_InformeFinCicloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCurso", DbType="VarChar(50)")]
		public string CodigoCurso
		{
			get
			{
				return this._CodigoCurso;
			}
			set
			{
				if ((this._CodigoCurso != value))
				{
					this._CodigoCurso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCurso", DbType="VarChar(150)")]
		public string NombreCurso
		{
			get
			{
				return this._NombreCurso;
			}
			set
			{
				if ((this._NombreCurso != value))
				{
					this._NombreCurso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProfesor", DbType="VarChar(602)")]
		public string NombreProfesor
		{
			get
			{
				return this._NombreProfesor;
			}
			set
			{
				if ((this._NombreProfesor != value))
				{
					this._NombreProfesor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaActualizacion", DbType="VarChar(30)")]
		public string FechaActualizacion
		{
			get
			{
				return this._FechaActualizacion;
			}
			set
			{
				if ((this._FechaActualizacion != value))
				{
					this._FechaActualizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Periodo", DbType="VarChar(50)")]
		public string Periodo
		{
			get
			{
				return this._Periodo;
			}
			set
			{
				if ((this._Periodo != value))
				{
					this._Periodo = value;
				}
			}
		}
	}
	
	public partial class up_Listar_ResultadoPrograma_x_CursoResult
	{
		
		private int _ResultadoProgramaId;
		
		private System.Nullable<int> _CarreraId;
		
		private string _Outcome;
		
		private string _Descripcion;
		
		public up_Listar_ResultadoPrograma_x_CursoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultadoProgramaId", DbType="Int NOT NULL")]
		public int ResultadoProgramaId
		{
			get
			{
				return this._ResultadoProgramaId;
			}
			set
			{
				if ((this._ResultadoProgramaId != value))
				{
					this._ResultadoProgramaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarreraId", DbType="Int")]
		public System.Nullable<int> CarreraId
		{
			get
			{
				return this._CarreraId;
			}
			set
			{
				if ((this._CarreraId != value))
				{
					this._CarreraId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Outcome", DbType="VarChar(5)")]
		public string Outcome
		{
			get
			{
				return this._Outcome;
			}
			set
			{
				if ((this._Outcome != value))
				{
					this._Outcome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class up_Obtener_InformeFinCicloResult
	{
		
		private int _InformeFinCicloId;
		
		private string _CoordinadorId;
		
		private int _CursoId;
		
		private int _PeriodoId;
		
		private string _DesarrolloUnidades;
		
		private string _ComentarioAlumnos;
		
		private string _ComentarioInfraestructura;
		
		private string _ComentarioDelegados;
		
		private string _ComentarioEscuesta;
		
		private string _Estado;
		
		private string _UltimaActualizacion;
		
		public up_Obtener_InformeFinCicloResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoordinadorId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CoordinadorId
		{
			get
			{
				return this._CoordinadorId;
			}
			set
			{
				if ((this._CoordinadorId != value))
				{
					this._CoordinadorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CursoId", DbType="Int NOT NULL")]
		public int CursoId
		{
			get
			{
				return this._CursoId;
			}
			set
			{
				if ((this._CursoId != value))
				{
					this._CursoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodoId", DbType="Int NOT NULL")]
		public int PeriodoId
		{
			get
			{
				return this._PeriodoId;
			}
			set
			{
				if ((this._PeriodoId != value))
				{
					this._PeriodoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DesarrolloUnidades", DbType="VarChar(500)")]
		public string DesarrolloUnidades
		{
			get
			{
				return this._DesarrolloUnidades;
			}
			set
			{
				if ((this._DesarrolloUnidades != value))
				{
					this._DesarrolloUnidades = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioAlumnos", DbType="VarChar(500)")]
		public string ComentarioAlumnos
		{
			get
			{
				return this._ComentarioAlumnos;
			}
			set
			{
				if ((this._ComentarioAlumnos != value))
				{
					this._ComentarioAlumnos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioInfraestructura", DbType="VarChar(500)")]
		public string ComentarioInfraestructura
		{
			get
			{
				return this._ComentarioInfraestructura;
			}
			set
			{
				if ((this._ComentarioInfraestructura != value))
				{
					this._ComentarioInfraestructura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioDelegados", DbType="VarChar(500)")]
		public string ComentarioDelegados
		{
			get
			{
				return this._ComentarioDelegados;
			}
			set
			{
				if ((this._ComentarioDelegados != value))
				{
					this._ComentarioDelegados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioEscuesta", DbType="VarChar(500)")]
		public string ComentarioEscuesta
		{
			get
			{
				return this._ComentarioEscuesta;
			}
			set
			{
				if ((this._ComentarioEscuesta != value))
				{
					this._ComentarioEscuesta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimaActualizacion", DbType="VarChar(30)")]
		public string UltimaActualizacion
		{
			get
			{
				return this._UltimaActualizacion;
			}
			set
			{
				if ((this._UltimaActualizacion != value))
				{
					this._UltimaActualizacion = value;
				}
			}
		}
	}
	
	public partial class up_Obtener_InformeFinCiclo_x_IdResult
	{
		
		private int _InformeFinCicloId;
		
		private string _CoordinadorId;
		
		private int _CursoId;
		
		private int _PeriodoId;
		
		private string _DesarrolloUnidades;
		
		private string _ComentarioAlumnos;
		
		private string _ComentarioInfraestructura;
		
		private string _ComentarioDelegados;
		
		private string _ComentarioEscuesta;
		
		private string _Estado;
		
		private string _UltimaActualizacion;
		
		public up_Obtener_InformeFinCiclo_x_IdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoordinadorId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CoordinadorId
		{
			get
			{
				return this._CoordinadorId;
			}
			set
			{
				if ((this._CoordinadorId != value))
				{
					this._CoordinadorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CursoId", DbType="Int NOT NULL")]
		public int CursoId
		{
			get
			{
				return this._CursoId;
			}
			set
			{
				if ((this._CursoId != value))
				{
					this._CursoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodoId", DbType="Int NOT NULL")]
		public int PeriodoId
		{
			get
			{
				return this._PeriodoId;
			}
			set
			{
				if ((this._PeriodoId != value))
				{
					this._PeriodoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DesarrolloUnidades", DbType="VarChar(500)")]
		public string DesarrolloUnidades
		{
			get
			{
				return this._DesarrolloUnidades;
			}
			set
			{
				if ((this._DesarrolloUnidades != value))
				{
					this._DesarrolloUnidades = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioAlumnos", DbType="VarChar(500)")]
		public string ComentarioAlumnos
		{
			get
			{
				return this._ComentarioAlumnos;
			}
			set
			{
				if ((this._ComentarioAlumnos != value))
				{
					this._ComentarioAlumnos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioInfraestructura", DbType="VarChar(500)")]
		public string ComentarioInfraestructura
		{
			get
			{
				return this._ComentarioInfraestructura;
			}
			set
			{
				if ((this._ComentarioInfraestructura != value))
				{
					this._ComentarioInfraestructura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioDelegados", DbType="VarChar(500)")]
		public string ComentarioDelegados
		{
			get
			{
				return this._ComentarioDelegados;
			}
			set
			{
				if ((this._ComentarioDelegados != value))
				{
					this._ComentarioDelegados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioEscuesta", DbType="VarChar(500)")]
		public string ComentarioEscuesta
		{
			get
			{
				return this._ComentarioEscuesta;
			}
			set
			{
				if ((this._ComentarioEscuesta != value))
				{
					this._ComentarioEscuesta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UltimaActualizacion", DbType="VarChar(30)")]
		public string UltimaActualizacion
		{
			get
			{
				return this._UltimaActualizacion;
			}
			set
			{
				if ((this._UltimaActualizacion != value))
				{
					this._UltimaActualizacion = value;
				}
			}
		}
	}
	
	public partial class up_Obtener_Logro_x_CursoResult
	{
		
		private int _LogroId;
		
		private int _CursoId;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estado;
		
		public up_Obtener_Logro_x_CursoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogroId", DbType="Int NOT NULL")]
		public int LogroId
		{
			get
			{
				return this._LogroId;
			}
			set
			{
				if ((this._LogroId != value))
				{
					this._LogroId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CursoId", DbType="Int NOT NULL")]
		public int CursoId
		{
			get
			{
				return this._CursoId;
			}
			set
			{
				if ((this._CursoId != value))
				{
					this._CursoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(5000)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit")]
		public System.Nullable<bool> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class up_Obtener_PeriodoActualResult
	{
		
		private int _PeriodoId;
		
		private string _Descripcion;
		
		private string _FechaInicio;
		
		private string _FechaFin;
		
		private System.Nullable<bool> _EsActual;
		
		public up_Obtener_PeriodoActualResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodoId", DbType="Int NOT NULL")]
		public int PeriodoId
		{
			get
			{
				return this._PeriodoId;
			}
			set
			{
				if ((this._PeriodoId != value))
				{
					this._PeriodoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="VarChar(30)")]
		public string FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this._FechaInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFin", DbType="VarChar(30)")]
		public string FechaFin
		{
			get
			{
				return this._FechaFin;
			}
			set
			{
				if ((this._FechaFin != value))
				{
					this._FechaFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsActual", DbType="Bit")]
		public System.Nullable<bool> EsActual
		{
			get
			{
				return this._EsActual;
			}
			set
			{
				if ((this._EsActual != value))
				{
					this._EsActual = value;
				}
			}
		}
	}
	
	public partial class up_Obtener_PersonaResult
	{
		
		private string _PersonaId;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private int _TipoPersona;
		
		public up_Obtener_PersonaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonaId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PersonaId
		{
			get
			{
				return this._PersonaId;
			}
			set
			{
				if ((this._PersonaId != value))
				{
					this._PersonaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(300)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(300)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this._Apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoPersona", DbType="Int NOT NULL")]
		public int TipoPersona
		{
			get
			{
				return this._TipoPersona;
			}
			set
			{
				if ((this._TipoPersona != value))
				{
					this._TipoPersona = value;
				}
			}
		}
	}
	
	public partial class up_Registrar_AccionMejoraResult
	{
		
		private int _AccionMejoraId;
		
		private int _HallazgoId;
		
		private int _InformeFinCicloId;
		
		private int _CicloEjecucionId;
		
		private string _Codigo;
		
		private string _Descripcion;
		
		private string _Estado;
		
		private bool _EstaActivo;
		
		private string _CodigoHallazgo;
		
		private string _CicloEjecucion;
		
		public up_Registrar_AccionMejoraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccionMejoraId", DbType="Int NOT NULL")]
		public int AccionMejoraId
		{
			get
			{
				return this._AccionMejoraId;
			}
			set
			{
				if ((this._AccionMejoraId != value))
				{
					this._AccionMejoraId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HallazgoId", DbType="Int NOT NULL")]
		public int HallazgoId
		{
			get
			{
				return this._HallazgoId;
			}
			set
			{
				if ((this._HallazgoId != value))
				{
					this._HallazgoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InformeFinCicloId", DbType="Int NOT NULL")]
		public int InformeFinCicloId
		{
			get
			{
				return this._InformeFinCicloId;
			}
			set
			{
				if ((this._InformeFinCicloId != value))
				{
					this._InformeFinCicloId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CicloEjecucionId", DbType="Int NOT NULL")]
		public int CicloEjecucionId
		{
			get
			{
				return this._CicloEjecucionId;
			}
			set
			{
				if ((this._CicloEjecucionId != value))
				{
					this._CicloEjecucionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(500)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstaActivo", DbType="Bit NOT NULL")]
		public bool EstaActivo
		{
			get
			{
				return this._EstaActivo;
			}
			set
			{
				if ((this._EstaActivo != value))
				{
					this._EstaActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoHallazgo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoHallazgo
		{
			get
			{
				return this._CodigoHallazgo;
			}
			set
			{
				if ((this._CodigoHallazgo != value))
				{
					this._CodigoHallazgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CicloEjecucion", DbType="VarChar(50)")]
		public string CicloEjecucion
		{
			get
			{
				return this._CicloEjecucion;
			}
			set
			{
				if ((this._CicloEjecucion != value))
				{
					this._CicloEjecucion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
