//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.OutcomeWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OutcomeCollectionDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract", ItemName="OutcomeDC")]
    [System.SerializableAttribute()]
    public class OutcomeCollectionDC : System.Collections.Generic.List<ConsoleApplication1.OutcomeWS.OutcomeDC> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutcomeDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class OutcomeDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutcomeDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OutcomeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutcomeNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutcomeDescripcion {
            get {
                return this.OutcomeDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeDescripcionField, value) != true)) {
                    this.OutcomeDescripcionField = value;
                    this.RaisePropertyChanged("OutcomeDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OutcomeId {
            get {
                return this.OutcomeIdField;
            }
            set {
                if ((this.OutcomeIdField.Equals(value) != true)) {
                    this.OutcomeIdField = value;
                    this.RaisePropertyChanged("OutcomeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutcomeNombre {
            get {
                return this.OutcomeNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeNombreField, value) != true)) {
                    this.OutcomeNombreField = value;
                    this.RaisePropertyChanged("OutcomeNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OutcomeWS.IOutcome")]
    public interface IOutcome {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOutcome/ListarOutcomePorCarreraId", ReplyAction="http://tempuri.org/IOutcome/ListarOutcomePorCarreraIdResponse")]
        ConsoleApplication1.OutcomeWS.OutcomeCollectionDC ListarOutcomePorCarreraId(int CarreraId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOutcomeChannel : ConsoleApplication1.OutcomeWS.IOutcome, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OutcomeClient : System.ServiceModel.ClientBase<ConsoleApplication1.OutcomeWS.IOutcome>, ConsoleApplication1.OutcomeWS.IOutcome {
        
        public OutcomeClient() {
        }
        
        public OutcomeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OutcomeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutcomeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutcomeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication1.OutcomeWS.OutcomeCollectionDC ListarOutcomePorCarreraId(int CarreraId) {
            return base.Channel.ListarOutcomePorCarreraId(CarreraId);
        }
    }
}
