//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.IFCDC.UI.ResultadoProgramaWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoProgramaxCursoCollectionDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class ResultadoProgramaxCursoCollectionDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaxCursoDC[] LstResultadoProgramaxCursoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaxCursoDC[] LstResultadoProgramaxCurso {
            get {
                return this.LstResultadoProgramaxCursoField;
            }
            set {
                if ((object.ReferenceEquals(this.LstResultadoProgramaxCursoField, value) != true)) {
                    this.LstResultadoProgramaxCursoField = value;
                    this.RaisePropertyChanged("LstResultadoProgramaxCurso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoProgramaxCursoDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class ResultadoProgramaxCursoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarreraIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CursoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricpionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutcomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultadoProgramaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarreraId {
            get {
                return this.CarreraIdField;
            }
            set {
                if ((this.CarreraIdField.Equals(value) != true)) {
                    this.CarreraIdField = value;
                    this.RaisePropertyChanged("CarreraId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CursoId {
            get {
                return this.CursoIdField;
            }
            set {
                if ((this.CursoIdField.Equals(value) != true)) {
                    this.CursoIdField = value;
                    this.RaisePropertyChanged("CursoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricpion {
            get {
                return this.DescricpionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricpionField, value) != true)) {
                    this.DescricpionField = value;
                    this.RaisePropertyChanged("Descricpion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Outcome {
            get {
                return this.OutcomeField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeField, value) != true)) {
                    this.OutcomeField = value;
                    this.RaisePropertyChanged("Outcome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultadoProgramaId {
            get {
                return this.ResultadoProgramaIdField;
            }
            set {
                if ((this.ResultadoProgramaIdField.Equals(value) != true)) {
                    this.ResultadoProgramaIdField = value;
                    this.RaisePropertyChanged("ResultadoProgramaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoProgramaXCarreraXPeriodoDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class ResultadoProgramaXCarreraXPeriodoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CarreraIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MallaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutcomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultadoProgramaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CarreraId {
            get {
                return this.CarreraIdField;
            }
            set {
                if ((this.CarreraIdField.Equals(value) != true)) {
                    this.CarreraIdField = value;
                    this.RaisePropertyChanged("CarreraId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MallaId {
            get {
                return this.MallaIdField;
            }
            set {
                if ((this.MallaIdField.Equals(value) != true)) {
                    this.MallaIdField = value;
                    this.RaisePropertyChanged("MallaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Outcome {
            get {
                return this.OutcomeField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeField, value) != true)) {
                    this.OutcomeField = value;
                    this.RaisePropertyChanged("Outcome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodoId {
            get {
                return this.PeriodoIdField;
            }
            set {
                if ((this.PeriodoIdField.Equals(value) != true)) {
                    this.PeriodoIdField = value;
                    this.RaisePropertyChanged("PeriodoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultadoProgramaId {
            get {
                return this.ResultadoProgramaIdField;
            }
            set {
                if ((this.ResultadoProgramaIdField.Equals(value) != true)) {
                    this.ResultadoProgramaIdField = value;
                    this.RaisePropertyChanged("ResultadoProgramaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoProgramaXCarreraXPeriodoCollectionDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class ResultadoProgramaXCarreraXPeriodoCollectionDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXCarreraXPeriodoDC[] lstResultadoProgramaXCarreraXPeriodoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXCarreraXPeriodoDC[] lstResultadoProgramaXCarreraXPeriodo {
            get {
                return this.lstResultadoProgramaXCarreraXPeriodoField;
            }
            set {
                if ((object.ReferenceEquals(this.lstResultadoProgramaXCarreraXPeriodoField, value) != true)) {
                    this.lstResultadoProgramaXCarreraXPeriodoField = value;
                    this.RaisePropertyChanged("lstResultadoProgramaXCarreraXPeriodo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoProgramaXMallaEncuestaXCarreraDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class ResultadoProgramaXMallaEncuestaXCarreraDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AsignadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CarreraIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MallaEncuestaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutcomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultadoProgramaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Asignado {
            get {
                return this.AsignadoField;
            }
            set {
                if ((this.AsignadoField.Equals(value) != true)) {
                    this.AsignadoField = value;
                    this.RaisePropertyChanged("Asignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CarreraId {
            get {
                return this.CarreraIdField;
            }
            set {
                if ((this.CarreraIdField.Equals(value) != true)) {
                    this.CarreraIdField = value;
                    this.RaisePropertyChanged("CarreraId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MallaEncuestaId {
            get {
                return this.MallaEncuestaIdField;
            }
            set {
                if ((this.MallaEncuestaIdField.Equals(value) != true)) {
                    this.MallaEncuestaIdField = value;
                    this.RaisePropertyChanged("MallaEncuestaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Outcome {
            get {
                return this.OutcomeField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeField, value) != true)) {
                    this.OutcomeField = value;
                    this.RaisePropertyChanged("Outcome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultadoProgramaId {
            get {
                return this.ResultadoProgramaIdField;
            }
            set {
                if ((this.ResultadoProgramaIdField.Equals(value) != true)) {
                    this.ResultadoProgramaIdField = value;
                    this.RaisePropertyChanged("ResultadoProgramaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoProgramaXMallaEncuestaXCarreraCollectionDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class ResultadoProgramaXMallaEncuestaXCarreraCollectionDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXMallaEncuestaXCarreraDC[] lstResultadoProgramaXMallaEncuestaXCarreraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXMallaEncuestaXCarreraDC[] lstResultadoProgramaXMallaEncuestaXCarrera {
            get {
                return this.lstResultadoProgramaXMallaEncuestaXCarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.lstResultadoProgramaXMallaEncuestaXCarreraField, value) != true)) {
                    this.lstResultadoProgramaXMallaEncuestaXCarreraField = value;
                    this.RaisePropertyChanged("lstResultadoProgramaXMallaEncuestaXCarrera");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoProgramaXMallaEncuestaDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class ResultadoProgramaXMallaEncuestaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AsignadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarreraIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MallaEncuestaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutcomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultadoProgramaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Asignado {
            get {
                return this.AsignadoField;
            }
            set {
                if ((this.AsignadoField.Equals(value) != true)) {
                    this.AsignadoField = value;
                    this.RaisePropertyChanged("Asignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarreraId {
            get {
                return this.CarreraIdField;
            }
            set {
                if ((this.CarreraIdField.Equals(value) != true)) {
                    this.CarreraIdField = value;
                    this.RaisePropertyChanged("CarreraId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MallaEncuestaId {
            get {
                return this.MallaEncuestaIdField;
            }
            set {
                if ((this.MallaEncuestaIdField.Equals(value) != true)) {
                    this.MallaEncuestaIdField = value;
                    this.RaisePropertyChanged("MallaEncuestaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Outcome {
            get {
                return this.OutcomeField;
            }
            set {
                if ((object.ReferenceEquals(this.OutcomeField, value) != true)) {
                    this.OutcomeField = value;
                    this.RaisePropertyChanged("Outcome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultadoProgramaId {
            get {
                return this.ResultadoProgramaIdField;
            }
            set {
                if ((this.ResultadoProgramaIdField.Equals(value) != true)) {
                    this.ResultadoProgramaIdField = value;
                    this.RaisePropertyChanged("ResultadoProgramaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoProgramaXCompetenciaAbetDC", Namespace="http://schemas.datacontract.org/2004/07/UPC.SSIA2013.WS.DataContract")]
    [System.SerializableAttribute()]
    public partial class ResultadoProgramaXCompetenciaAbetDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AsignadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarreraIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompetenciaAbetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MallaEncuestaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultadoProgramaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Asignado {
            get {
                return this.AsignadoField;
            }
            set {
                if ((this.AsignadoField.Equals(value) != true)) {
                    this.AsignadoField = value;
                    this.RaisePropertyChanged("Asignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarreraId {
            get {
                return this.CarreraIdField;
            }
            set {
                if ((this.CarreraIdField.Equals(value) != true)) {
                    this.CarreraIdField = value;
                    this.RaisePropertyChanged("CarreraId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompetenciaAbetId {
            get {
                return this.CompetenciaAbetIdField;
            }
            set {
                if ((this.CompetenciaAbetIdField.Equals(value) != true)) {
                    this.CompetenciaAbetIdField = value;
                    this.RaisePropertyChanged("CompetenciaAbetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaModificacionField, value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaRegistroField, value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MallaEncuestaId {
            get {
                return this.MallaEncuestaIdField;
            }
            set {
                if ((this.MallaEncuestaIdField.Equals(value) != true)) {
                    this.MallaEncuestaIdField = value;
                    this.RaisePropertyChanged("MallaEncuestaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodoId {
            get {
                return this.PeriodoIdField;
            }
            set {
                if ((this.PeriodoIdField.Equals(value) != true)) {
                    this.PeriodoIdField = value;
                    this.RaisePropertyChanged("PeriodoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultadoProgramaId {
            get {
                return this.ResultadoProgramaIdField;
            }
            set {
                if ((this.ResultadoProgramaIdField.Equals(value) != true)) {
                    this.ResultadoProgramaIdField = value;
                    this.RaisePropertyChanged("ResultadoProgramaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResultadoProgramaWS.IResultadoPrograma")]
    public interface IResultadoPrograma {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResultadoPrograma/WSListarResultadoProgramaxCurso", ReplyAction="http://tempuri.org/IResultadoPrograma/WSListarResultadoProgramaxCursoResponse")]
        UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaxCursoCollectionDC WSListarResultadoProgramaxCurso(int cursoId, int periodoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResultadoPrograma/ListarResultadoProgramaXCarreraXPeriodo", ReplyAction="http://tempuri.org/IResultadoPrograma/ListarResultadoProgramaXCarreraXPeriodoResp" +
            "onse")]
        UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXCarreraXPeriodoCollectionDC ListarResultadoProgramaXCarreraXPeriodo(UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXCarreraXPeriodoDC objDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResultadoPrograma/ListarResultadoProgramaXMallaEncuestaXCarre" +
            "ra", ReplyAction="http://tempuri.org/IResultadoPrograma/ListarResultadoProgramaXMallaEncuestaXCarre" +
            "raResponse")]
        UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXMallaEncuestaXCarreraCollectionDC ListarResultadoProgramaXMallaEncuestaXCarrera(UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXMallaEncuestaXCarreraDC objDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResultadoPrograma/RegistrarResultadoProgramaXMallaEncuesta", ReplyAction="http://tempuri.org/IResultadoPrograma/RegistrarResultadoProgramaXMallaEncuestaRes" +
            "ponse")]
        int RegistrarResultadoProgramaXMallaEncuesta(UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXMallaEncuestaDC[] lstDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResultadoPrograma/RegistrarResultadoProgramaXCompetenciaAbet", ReplyAction="http://tempuri.org/IResultadoPrograma/RegistrarResultadoProgramaXCompetenciaAbetR" +
            "esponse")]
        int RegistrarResultadoProgramaXCompetenciaAbet(UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXCompetenciaAbetDC[] lstDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResultadoPrograma/ActualizarResultadoProgramaxMallaEncuesta", ReplyAction="http://tempuri.org/IResultadoPrograma/ActualizarResultadoProgramaxMallaEncuestaRe" +
            "sponse")]
        int ActualizarResultadoProgramaxMallaEncuesta(UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXMallaEncuestaDC[] lstLR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResultadoPrograma/ActualizarResultadoProgramaxCompetenciaAbet" +
            "", ReplyAction="http://tempuri.org/IResultadoPrograma/ActualizarResultadoProgramaxCompetenciaAbet" +
            "Response")]
        int ActualizarResultadoProgramaxCompetenciaAbet(UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXCompetenciaAbetDC[] lstLR);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResultadoProgramaChannel : UPC.IFCDC.UI.ResultadoProgramaWS.IResultadoPrograma, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResultadoProgramaClient : System.ServiceModel.ClientBase<UPC.IFCDC.UI.ResultadoProgramaWS.IResultadoPrograma>, UPC.IFCDC.UI.ResultadoProgramaWS.IResultadoPrograma {
        
        public ResultadoProgramaClient() {
        }
        
        public ResultadoProgramaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResultadoProgramaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResultadoProgramaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResultadoProgramaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaxCursoCollectionDC WSListarResultadoProgramaxCurso(int cursoId, int periodoId) {
            return base.Channel.WSListarResultadoProgramaxCurso(cursoId, periodoId);
        }
        
        public UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXCarreraXPeriodoCollectionDC ListarResultadoProgramaXCarreraXPeriodo(UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXCarreraXPeriodoDC objDC) {
            return base.Channel.ListarResultadoProgramaXCarreraXPeriodo(objDC);
        }
        
        public UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXMallaEncuestaXCarreraCollectionDC ListarResultadoProgramaXMallaEncuestaXCarrera(UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXMallaEncuestaXCarreraDC objDC) {
            return base.Channel.ListarResultadoProgramaXMallaEncuestaXCarrera(objDC);
        }
        
        public int RegistrarResultadoProgramaXMallaEncuesta(UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXMallaEncuestaDC[] lstDC) {
            return base.Channel.RegistrarResultadoProgramaXMallaEncuesta(lstDC);
        }
        
        public int RegistrarResultadoProgramaXCompetenciaAbet(UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXCompetenciaAbetDC[] lstDC) {
            return base.Channel.RegistrarResultadoProgramaXCompetenciaAbet(lstDC);
        }
        
        public int ActualizarResultadoProgramaxMallaEncuesta(UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXMallaEncuestaDC[] lstLR) {
            return base.Channel.ActualizarResultadoProgramaxMallaEncuesta(lstLR);
        }
        
        public int ActualizarResultadoProgramaxCompetenciaAbet(UPC.IFCDC.UI.ResultadoProgramaWS.ResultadoProgramaXCompetenciaAbetDC[] lstLR) {
            return base.Channel.ActualizarResultadoProgramaxCompetenciaAbet(lstLR);
        }
    }
}
